import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//  Ce composant est le composant de mise en page racine de notre application. Il enveloppe tous les composants de notre application et définit les métadonnées de la page.
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
